### ISSUE TITLE
re: Loading on page load

### ISSUE THREAD

**Issue by anartfulscience** [mds/readable#7]
Thanks for making this widget. It's come in handy :)

The only thing is that it's loading on page load initially, then after a few seconds disappearing. 
Could it function that it only loads when the user clicks a link?

Thanks, Stephen

**Comment by mds** [comment]
It definitely could, but it was designed to function like that for the demo site.

I made it load and then disappear to show it turning on and off for the first time visitor. 
Kind of like, "Hey, look at me. I'm doing this thing and you can too."

You can disable that by editing the function call in the JS.
